pipeline {
    environment {
        registry = "phiroict/k8s-test-frontend"
        registryCredential = 'dockerhub-creds'
    }

    agent any
    stages {
        stage('Build') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'ssh', url: 'git@github.com:phiroict/PoC_py_frontend.git']]])
                script {
                    sh ("docker build -t ${registry}:$BUILD_NUMBER")
                    def sha256 = sh(returnStdout: true, script: "docker push ${registry}:${BUILD_NUMBER}")
                    echo "Value of the return is ${sha256}"
//                     docker.withRegistry("https://registry.hub.docker.com", registryCredential) {
//                         def image = docker.build(registry + ":$BUILD_NUMBER")
//                         image.push()
//                     }
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing"
            }
        }
        stage('Deploy') {
            steps {
                echo "Pushing sha to repo"
            }
        }
    }
}