pipeline {
    environment {
        registry = "phiroict/k8s-test-frontend"
        registryCredential = 'dockerhub-creds'
    }
    agent any
    stages {
        stage('Build') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'ssh', url: 'git@github.com:phiroict/PoC_py_frontend.git']]])
                script {

                    docker.withRegistry("https://hub.docker.com", registryCredential) {
                        def image = docker.build(registry + ":$BUILD_NUMBER")
                        image.push()
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing"
            }
        }
        stage('Deploy') {
            steps {
                echo "Pushing sha to repo"
            }
        }
    }
}