#!/bin/sh

export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
export XDG_MENU_PREFIX="gnome-flashback-"
unset SESSION_MANAGER
exec /etc/X11/xinit/xinitrc

gnome-session --debug --session=gnome-flashback-metacity --disable-acceleration-check &
vncconfig -iconic &
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &
